### PR TITLE
Configure & document :courseTest/:tastyTest

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by ajmcmiddlin** [comment]
Cool! I'm now wondering if we should just add `:courseTest` and `:tastyTest` commands to the course `.ghci` file so we just have to tell users that they exist and how to use them.

**Comment by dwijnand** [comment]
Sure, can do!  Good idea.

**Comment by dwijnand** [comment]
Is the CI validation failure unrelated to this PR, or am I mistaken?

**Comment by ajmcmiddlin** [comment]
@dwijnand Sorry for dropping the ball on this one! The build failure was indeed unrelated to your changes. CI is fixed up, and this has been merged. Thanks again for the contribution.

**Pull request merged**
