### PR TITLE
make learning haskell silky smooth with zero friction

### PR DESCRIPTION
**Pull request by ghuntley**
Howdy folks,

I've learned so much from you over the years and it's time to start giving back. 

This pull-request completely removes all friction and enables educators to deliver this course without having to ask students to download or configure anything. It provides certainty that all students are using  exactly the same classroom environment. 

image

With a small amount of tweaking it would be possible to do language server integration with the editor via https://github.com/Infinisil/all-hies to enable magical things such as:

Diagnostics via hlint and GHC warnings/errors

Auto Completion

Code actions and quick fixes via apply-refact

Type information and documentation(via haddock) on hover

Jump to definition

List all top level definitions

Highlight references in document

Formatting via brittany

Renaming via HaRe

To get HIE functioning we need to wire HIE into `fp-course/default.nix` and then expose the binaries `ghc` and `hies` out to the editor.

### CODE REVIEW

**Comment by ghuntley** [comment]
Here's how you use it:

1. Ask students to visit https://gitpod.io/#https://github.com/data61/fp-course

That's it.

**Comment by ghuntley** [comment]
The latest commits added to this PR enables a similar experience for people using visual studio code on mac, linux and windows. When a student clones the repository and opens the folder in vscode they will be prompted as follows:

image

When `Reopen in Container` is selected it will relaunch visual studio code and in the background, completely seamless to the student the `.devcontainer/Dockerfile` will be build, the nix-cache will be populated and then the git repository will be mounted in the docker container. 

From the students point-of-view the end result looks like this:

image

**Comment by puffnfresh** [comment]
@ghuntley I'm using your branch link but I'm not getting syntax highlighting nor any of these features. I do see a nix-shell open up at the bottom. Is there another step I'm missing?

**Comment by ghuntley** [comment]
HIE features aren't wired into GitPod at the moment. The last force push I did in theory wires them into vscode but I haven't tested yet.

**Comment by ghuntley** [comment]
As this PR currently stands at the moment. 

This PR allows people to start doing the course without downloading anything. All they need is a GitHub account.

This PR allows people to start doing the course using any operating system in a desktop app without having to do anything more than cloning the repository and opening it in vscode.

In both of the above scenarios behind the scenes is nix running in Docker but hidden from the user.

**Comment by puffnfresh** [comment]
Quickly trying this out on NixOS with:

```nix
vscode-with-extensions.override {
  vscode = (vscode.override { isInsiders = true; }).overrideDerivation (drv: rec {
    name = "vscode-${version}";
    version = "1557850607";
    src = fetchurl {
      url = "https://vscode-update.azurewebsites.net/latest/linux-x64/insider";
      sha256 = "1np8nqmmj7pcr61hdfm94npvqb1xrvixam0qv9sfqlbakbx4bwl6";
      name ="code_x64_${version}.tar.gz";
    };
  });
  vscodeExtensions = vscode-utils.extensionsFromVscodeMarketplace [ {
    name = "remote-containers";
    publisher = "ms-vscode-remote";
    version = "0.63.0";
    sha256 = "0z77kk9cmws3zc13z16y64kfmy6rg36p8pz1gidy8hdjmx4m4kv5";
  } ];
}
```

Contains a URL which mutates. The hash will only work for one day.

**Comment by Rizary** [comment]
Hi, this PR is great (as I am now working on both of data61 course). One thing that I want to ask is, does this PR only for Docker container? How about WSL? I have no luck to make it work on WSL though. Sorry if this is not relevance.

**Comment by ghuntley** [comment]
Hey @Rizary. When you open https://github.com/data61/fp-course/pull/340#issuecomment-504848348 in vscode preview everything will be seamless. WSL2 was recently released and the windows docker engine is moving to it. Likewise keep an eye on https://github.com/NixOS/nixpkgs/pull/63049 which brings NixOS to WSL.

**Comment by Rizary** [comment]
@ghuntley hi.. that is nice!! Right now, I'm using WSL almost for all my project (inc. my google summer of code project). I already install all-hies and got the weird error in like in here: https://github.com/alanz/vscode-hie-server/issues/128#issuecomment-505231054.

**Comment by benkolera** [comment]
Thanks @ghuntley . This looks awesome! 

Just so that you don't think that we're ignoring you or don't like your work, we are currently figuring out how to make sure how to frame this new stuff with respect to our in-person courses. It is super awesome that folk online can start the course after clicking a link, but it could be problematic if we have 60 people show up to an in-person course all wanting to use the web gitpod version on lousy Australian wifi.  :slightly_smiling_face: The courses -- like any workshop -- can start off a little hectic, so we just need to be a little bit careful before we mess with the existing process. And we are especially conservative because we have an in-person course in 8 days! :joy: 

Even if the gitpod side of things is mainly useful for non in-person work, this is still super helpful as we want to make this course more easily consumed by folk that can't come along to our classes. That should help a lot. Also, the code remote side should be a level up over plain GHC if we get the tooling working nice and should just be easier than installing ghc. So thanks for pointing out that rad vs-code plugin for running the shell tooling in a docker container!

**Comment by ghuntley** [comment]
nps @benkolera. See also https://github.com/digital-asset/daml/tree/master/compiler/hie-core#readme and https://twitter.com/ndm_haskell/status/1145700783440179201

**Comment by benkolera** [comment]
@ghuntley Oh cool! I've been seeing Matthew Pickering's work on the hie-bios and splitting up hie as part of that and it looks like a good refactoring step. I didn't realise that DA had already done the same with their tooling. Cool. :)

**Comment by dalaing** [comment]
Awesome - thanks @ghuntley!

**Pull request merged**
