### PR TITLE
Rename failed since now it can be used to not fail

### LINKED ISSUE #229: Update docs and name of `Parser.fail`
`fail` does not always return a failing parser as it [used to](https://github.com/tonymorris/fp-course/blob/master/src/Course/Parser.hs#L93).

```haskell
λ> isErrorResult $ parse (failed (Result "foo" 42)) "cat"
False
```

### PR DESCRIPTION
**Pull request by gwils**
closes #229 

This is kind of a crummy name. Happy to change to a better one if there's a suggestion.

### CODE REVIEW

**Comment by ajmccluskey** [comment]
Would `always` be better? Naming is hard...

**Comment by tonymorris** [comment]
Naming is hard

**Comment by gwils** [comment]
`always` is a worse name in my opinion, because the English vocabulary for parsers used in this part of the course says "always" translates into `pure`.

**Comment by ajmccluskey** [comment]
@gwils makes sense. I have no other suggestions at this time :)

**Comment by gwils** [comment]
@tonymorris Naming is hard, but I think this is better than the current state of things. What do you reckon?

**Comment by tonymorris** [comment]
Do it.

**Pull request merged**
